Remove nullability annotations from primitive fields
FoundationDB/fdb-record-layer pull request #1060
Opened 2020-10-28 23:07 UTC by MMcM

2020-10-28 23:09 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/KeyValueCursor.java
> +    @Nonnull
Always initialized non-null (same IDE inspection).

2020-10-29 16:20 UTC, alecgrieser approved these changes

2020-10-29 16:22 UTC, alecgrieser requested changes
Approved pending spot bugs rule resolution (which is apparently what caused the prb to fail, though it looks like the rule violation itself wasn't saved in the build artifacts)

2020-10-29 20:58 UTC, alecgrieser approved these changes

2020-10-29 20:58 UTC, merged