fixing NPE on planHash call for lucene
FoundationDB/fdb-record-layer pull request #1234
Opened 2021-04-16 14:38 UTC by sophiabuell

2021-04-16 16:12 UTC, sophiabuell commented
test this please

2021-04-16 19:50 UTC, normen662 requested changes

2021-04-16 19:50 UTC, normen662 commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java
> +                return indexName.hashCode() + scanType.planHash(hashKind) + comparisons.planHash(hashKind) + (sort != null ? sort.planHash() : 0) + (reverse ? 1 : 0);
There is no real LEGACY here as lucene is new. How about you just treat `LEGACY` and `STRUCTURAL_WITHOUT_LITERALS` the same,.

2021-04-16 19:50 UTC, normen662 commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexQueryPlan.java
> +                return indexName.hashCode() + scanType.planHash(hashKind) + comparisons.planHash(hashKind) + (sort != null ? sort.planHash() : 0) + (reverse ? 1 : 0);
In other words just more the `case LEGACY:` a few lines down.

2021-04-20 01:50 UTC, normen662 approved these changes

2021-04-20 01:50 UTC, merged