Deal with asynchrony issues in FDBDirectory
FoundationDB/fdb-record-layer pull request #1333
Opened 2021-07-22 14:07 UTC by scottfines

see #1322 for more information about the bug. This fix is somewhat temporary, and accomplishes 3 things:

1. Resolves some spotty blocking calls in `FDBDirectory` so that they block less
2. Ensures that the forced synchronous methods in `FDBDirectory` are not called on the context's executor, to avoid deadlocks (still potential performance problems due to waiting for an open FJ thread, but at least it's less likely to actually break)
3. Add the ability to ignore blocking in asynchronous methods when we know that they are safe (for now)

A very good question would be: why do we have to be asynchronous here? and the answer is--because Lucene requires us to, and I'm not in a position to rewrite Lucene's entire API in order to support asynchronous method execution (I'm not even really sure that Lucene's thread model would support it). So here we are.

In the long term, we'll need to move blocking operations to a separate blocking thread pool in order to avoid potential performance bottlenecks, but this should serve in the short term.

2021-07-22 15:37 UTC, scottfines commented
test this please

2021-07-22 16:23 UTC, scgray requested changes

2021-07-22 16:23 UTC, scgray commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabase.java
> +    private boolean canIgnoreBlockingInAsync(final String className, final String methodName) {
This should probably have a test added in `FDBDatabaseTest` (there is a suite of tests around this named `testBlockingInAsync*`

2021-07-22 16:23 UTC, scgray commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
> +        } catch (ExecutionException ee) {
I think this can all be replaced with:

```
catch (Exception e) {
   throw FDBExceptions.wrap(e);
}
```

2021-07-27 17:10 UTC, ScottDugas requested changes

2021-07-27 17:10 UTC, ScottDugas commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
> +        return context.ensureActive().getRange(metaSubspace.range()).asList().thenApply(keyValues -> {
What thread pool does this happen on?

2021-07-27 17:10 UTC, ScottDugas commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
>              return context.instrument(FDBStoreTimer.Events.LUCENE_GET_FILE_REFERENCE, context.ensureActive().get(metaSubspace.pack(name))
What thread pool does this run on? The annotation gets added to the method where `asyncToSync` is called, correct? In that case it seems like this method should document what thread pool its future is running on.

2021-07-27 17:10 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryTest.java
> -        assertCorrectMetricCount(FDBStoreTimer.Waits.WAIT_LUCENE_DELETE_FILE,2);
Why did this change from 2 to 1?

2021-07-27 17:10 UTC, ScottDugas commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectory.java
> +         * operations like this, but in the short term, use the default FJ pool (see deleteFile for a more detailed
```suggestion
         * operations like this, but in the short term, use the default fork-join pool (see deleteFile for a more detailed
```

2022-09-23 07:41 UTC, ngbinh commented
Hi, we encountered cases of deadlocks when using record layer lucene indexes. Is there a plan to finish this PR? Thanks

2022-09-23 18:53 UTC, MMcM commented
> Hi, we encountered cases of deadlocks when using record layer lucene indexes. Is there a plan to finish this PR? Thanks

Do you attribute these deadlocks to something like fork-join pool exhaustion? I'd like to confirm that the bugs addressed here will fix your cases.

2022-09-24 01:24 UTC, ngbinh commented
@MMcM Yes. Under heavy load on records with Lucene indexes enabled, all the workers on the FJ pool are exhausted.

2025-05-20 13:08 UTC, arnaud-lacurie commented
Closing old PR. This can be reopened later if need be.

2025-05-20 13:08 UTC, closed without merging