Ordering refactorings
FoundationDB/fdb-record-layer pull request #1474
Opened 2021-11-27 07:31 UTC by normen662

2021-12-06 08:10 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/Ordering.java
> +        final var ordering = (Ordering)o;
Done. Thanks!

2021-12-06 08:13 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/RequestedOrdering.java
> +        return getOrderingKeyParts().equals(ordering.getOrderingKeyParts());
Done.

2021-12-06 08:18 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/MatchInfo.java
> +            if (boundKeyPart.isReverse() && allForward) {
You are right. Changed.

2021-12-06 08:38 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/TopologicalSort.java
> +public class TopologicalSort {
There are a few reasons:
- this is code that was just moved in this PR so I am not really introducing something new
- I looked at jgrapht (before I added these classes) when I added the matching code and the explain (DOT) code and jgrapht has some disadvantages in general (LPL and some weird design choices) + Guava has a pretty good graph package that we actually went for (in fact I rewrote an already existing JGraphT implementation to use Guava)
- this iterator AFAICT is giving you exactly one topological sort order element-by-element. `TopologicalSort` as implemented in rec layer gives you an iterator over all the topologically valid sort orders (so each item the iterator returns is a list of items in topologically valid order).
- our iterators can skip subspaces of the search space (see `skip(int)`)
- we have two different ways of iteration: one is a backtracking iterator that in general is faster for cases where you don't have that many dependencies (orderings) between items; and Kahn's algorithm which is way better when enumerating topological orders of elements that almost define complete ordering among their items. In almost every prepackaged algorithm that comes with a graph library you'll get Kahn's algorithm which tends to become very slow if your degrees of freedom are high

2021-12-06 08:50 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/PartialOrder.java
> +public class PartialOrder<T> {
Done.

2021-12-06 14:51 UTC, ohadzeliger approved these changes

2021-12-07 23:04 UTC, MMcM requested changes

2021-12-08 18:26 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/EnumeratingIterable.java
> +     * input sets. Iterators created by this class, however, avoid to build complex state objects
Done.

2021-12-08 18:27 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/PartialOrder.java
> +     * A class allowing to compute a subset of elements in a partial order that are said to be <em>eligible</em>eligible.
Done.

2021-12-08 20:35 UTC, MMcM approved these changes

2021-12-09 08:50 UTC, merged