Resolves #1520: Expose IndexQueryabilityFilter for Aggregate planning
FoundationDB/fdb-record-layer pull request #1523
Opened 2022-02-04 22:33 UTC by ScottDugas

For IndexFunctionHelper and ComposedBitmapIndexAggregate, this change
adds it as a required parameter.

Since FDBRecordStoreBase is MAINTAINED this adds overloads for:
- getSnapshotRecordCountForRecordType
- evaluateAggregateFunction
that take the IndexQueryabilityFilter, using TRUE to maintain
backwards compatibility. The old method is left as a default
method, requiring implementers to add the new method.

2022-02-05 03:27 UTC, ohadzeliger requested changes
Looks good, just a few (minor) comments.

2022-02-05 03:27 UTC, ohadzeliger commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java
> +     * consulted if the aggregateFunction already has an index
```suggestion
     * consulted if the aggregateFunction already has a readable index
```

2022-02-07 15:40 UTC, ScottDugas commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStoreBase.java
> +    default CompletableFuture<Long> getSnapshotRecordCountForRecordType(@Nonnull String recordTypeName) {
There's almost certainly places that evaluate against indexes which may be filtered, but I did the other methods here.

2022-02-07 15:41 UTC, ScottDugas commented
Rebased to address conflicts in ReleaseNotes

2022-02-07 16:15 UTC, ohadzeliger submitted a review, later dismissed

2022-02-07 16:52 UTC, ohadzeliger approved these changes

2022-02-07 16:53 UTC, merged