grouped indexes using rank()
FoundationDB/fdb-record-layer pull request #1542
Opened 2022-03-03 01:52 UTC by normen662

2022-03-04 01:05 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/temp/explain/DotExporter.java
> +        if (childrenEdges.stream().allMatch(edge -> edge.getDependsOn().isEmpty())) {
Note to reviewer: This is some layout improvement for the internal explain, i.e. the explain that is only used for debugging purposes. Disregard changes as they are complicated and only improve the rendering of the boxes.

2022-03-10 05:29 UTC, MMcM requested changes

2022-03-11 21:19 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
> +            return getParameter().equals(that.getParameter());
done.

2022-03-11 21:20 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/predicates/AndPredicate.java
> +                .collect(Collectors.joining(" and "));
done.

2022-03-14 06:42 UTC, MMcM approved these changes

2022-03-14 06:43 UTC, merged