Resolves #1580: Lucene index maintainer should support delete where on group key
FoundationDB/fdb-record-layer pull request #1582
Opened 2022-04-02 01:23 UTC by alecgrieser

This also fixes additional problems that were found with delete records where with grouped keys. In particular, the atomic mutation and rank indexes weren't checking that the delete where predicate was just over the grouping key, and so it would allow delete records where in cases where it shouldn't. This addresses that problem and adds some tests of rank and sum indexes to make that point. The text index was already making that check, but that's now tested (which it didn't seem to be before). Similar tests to the `TEXT` index was added for the `LUCENE` index.

wip: still needs to clear out state that is cached in memory

2022-04-07 18:53 UTC, alecgrieser commented
This will conflict with #1584, but I've decoupled the two changes, so whichever merges first just needs to fix conflicts with the other one

2022-04-07 20:29 UTC, alecgrieser commented
Okay, the latest push includes a fixed up merge. It also includes a fix for #1598, which was breaking the build. That's identical to the commit in #1599, which I broke out as it should be breaking everyone else, too, but if #1599 merges first, this PR may need a rebase

2022-04-14 23:01 UTC, tian-yizuo requested changes
LGTM basically, just a minor comment

2022-04-14 23:18 UTC, alecgrieser commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java
> +class FDBDirectoryWrapper implements AutoCloseable {
Added some to this class

2022-04-14 23:20 UTC, alecgrieser commented
Rebase addresses merge conflicts. The primary one that was a little tricky to resolve was in `AutoCompleteSuggesterCommitCheckAsync.java` to use the `LuceneOptimizedWrappedBlendedInfixSuggester` when it creates the suggester

2022-04-14 23:22 UTC, tian-yizuo approved these changes

2022-04-14 23:58 UTC, merged