join enumeration using dynamic programming
FoundationDB/fdb-record-layer pull request #1695
Opened 2022-05-25 04:43 UTC by normen662

2022-05-30 20:12 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NullValue.java
> +public class NullValue implements LeafValue {
This is a welcome addition!

2022-05-30 20:12 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NullValue.java
> +public class NullValue implements LeafValue {
This is a welcome addition!

2022-05-30 20:12 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NullValue.java
> +        return true;
should this be `false`?

2022-05-30 20:12 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NullValue.java
> +        return true;
should this be `false`?

2022-05-31 06:07 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
> +            }
It's allowed for it to be unbound. In fact for Valkyrie it would always be unbound I think.

2022-05-31 06:10 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
> +            // No additional validation.
The type system takes care of this. This validate is usually for user-specified comparisons like literal comparisons and parameter comparisons which are part of the query, not some internal construct solely used for planning. This comparison is a construct of planning and we can assume that the flowed data is conform to the type (at least at this place).

2022-05-31 06:10 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/expressions/Comparisons.java
> +            // No additional validation.
see above

2022-05-31 06:13 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/bitmap/ComposedBitmapIndexQueryPlan.java
> +                allAreSame = false;
Break at that place would be incorrect as all children need to be translated. Only if none of them come back different you can use the current instance.

2022-05-31 06:15 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/ExpressionRefs.java
> +        for (final var expressionRef : expressionRefs) {
That is correct. Rebasing a graph (or translating its correlations) need to be cognizant of the common sub expressions and need to do its job without breaking them, i.e. making the CSE non-CSEs, or in other words making the DAG a tree instead which is what is happening prior to this checkin.

2022-05-31 06:18 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraph.java
> +                    .orElseThrow(() -> new RecordCoreException("should have found the quantifier")); // not great, not terrible
So the planner graph has a lower standard of assumptions build in. The reasoning is that while you cannot plan/execute any QGM that is structurally unsound, you may want to still be able to look at the incorrect graph for debugging purposes. Thus, for the `PlannerGraph` codepath we try to be as forgiving as possible.

2022-05-31 06:21 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraph.java
> +                            .collect(ImmutableSet.toImmutableSet());
The `PlannerGraph` is created as an adjacent data structure upon request (like for explain or the `.show()` you can do in the debugger. `PlannerGraph` is always built based on top of a QGM (the truth is there). Having a separate structure allows the `PlannerGraph` to worry about graphical attributes, namings and even graphing improvements. For instance, `SCAN(T)` is one `RelationalExpression` but it's two nodes in the explain.

2022-05-31 06:23 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraph.java
> +                            .collect(ImmutableSet.toImmutableSet());
These `PlannerGraph` things are a result of walking the QGM. `PlannerGraph` is solely used to export a QGM into `GML` or `DOT`. For those purposes it seemed like a secondary graph was easier to work with as QGM didn't need to be polite to hold rendering information, etc.

2022-05-31 06:25 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java
> +        return outerCardinalities.times(innerCardinalities);
This is `Cardinalities`, not `Cardinality`

2022-05-31 06:27 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryExplodePlan.java
> +public class RecordQueryExplodePlan implements RecordQueryPlanWithNoChildren {
Explode is a leaf level plan operator, so it's not like `map` or `flatmap` which  operate on a stream of records.

2022-05-31 06:28 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/NullValue.java
> +        return true;
good catch

2022-05-31 06:32 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
> + */
done

2022-06-02 15:34 UTC, MMcM requested changes

2022-06-02 15:34 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java
> + * This property establishes a partial order over the expressions contained in a subgraph.
Copied from another class?

2022-06-03 20:13 UTC, MMcM requested changes

2022-06-03 20:13 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
> + * i.e. does not produce any records, are default value that is passed into the constructor is returned in place of
```suggestion
 * i.e. does not produce any records, a default value that is passed into the constructor is returned in place of
```
```suggestion
 * i.e. does not produce any records, are default value that is passed into the constructor is returned in place of
```

2022-06-03 20:13 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
> + * i.e. does not produce any records, are default value that is passed into the constructor is returned in place of
```suggestion
 * i.e. does not produce any records, a default value that is passed into the constructor is returned in place of
```

2022-06-03 20:13 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
> + * i.e. does not produce any records, are default value that is passed into the constructor is returned in place of
```suggestion
 * i.e. does not produce any records, a default value that is passed into the constructor is returned in place of
```

2022-06-13 06:39 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/explain/PlannerGraph.java
> +                            .collect(ImmutableSet.toImmutableSet());
Addendum, join order is _NOT_ modeled by the ordinal position of the quantifiers in an expression, the order is informed but the `correlatedTo()`-sets retrieved from each individual quantifier going into an expression.

2022-06-13 06:50 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/properties/CardinalitiesProperty.java
> + * This property establishes a partial order over the expressions contained in a subgraph.
Fixed.

2022-06-13 06:54 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/combinatorics/TopologicalSort.java
> +     * @return a permutation of the set that is topologically correctly ordered with respect to {@code dependsOnFn}
There are three overloads for this method that all directly of indirectly transform the given `depends-on` information into a `PartialOrder`. I will rewrite the docs to say something like `...dependency relationships between the items in the given set`

2022-06-13 06:57 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryFirstOrDefaultPlan.java
> + * i.e. does not produce any records, are default value that is passed into the constructor is returned in place of
done.

2022-06-13 13:56 UTC, hatyo commented
LGTM

2022-06-13 15:09 UTC, merged