Return null when a field is not set
FoundationDB/fdb-record-layer pull request #1807
Opened 2022-07-26 22:05 UTC by pengpeng-lu

* For repeated field, it returns empty array if not set.

2022-07-29 15:24 UTC, hatyo approved these changes

2022-07-29 15:24 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageValue.java
> +    }
It would be really nice to add some documentation if possible (same for other newly-added methods).

2022-08-01 23:01 UTC, normen662 requested changes

2022-08-01 23:01 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/MessageValue.java
> +    private static Object getFieldOnMessage(@Nonnull MessageOrBuilder message, @Nonnull Descriptors.FieldDescriptor field) {
Wouldn't you have to unnest a wrapped value here?

2022-08-01 23:03 UTC, normen662 requested changes
So the thing that is missing here is that we want to unnest the wrapped value if it was in fact nested for this null-valued collections. Also if we do that we will also need to wrap it back into it's nested form for `RecordConstructorValue`s. Sorry, if you wanted to keep this separated into a different PR.

2022-08-01 23:08 UTC, normen662 approved these changes

2022-08-01 23:08 UTC, merged