Fix #1898: Indexing: periodic "Built Range" log message is broken
FoundationDB/fdb-record-layer pull request #1899
Opened 2022-11-07 21:04 UTC by jjezra

2022-11-07 21:18 UTC, jleach4 requested changes
Test?

2022-11-07 21:22 UTC, jjezra commented
> Test?

I've verified that the log message appears in some of the existing tests. Example: 
```
2022-11-07 15:54:55,826 [INFO] c.a.f.r.p.f.IndexingBase - Indexer: Built Range calling_method="buildMultiTargetIndex" delay="1" indexer_id="c016639b-30cc-47d4-98bd-5810e2bd4186" indexing_method="multi target by records" limit="17" range_end="null" range_start="null" records_per_second="10000" records_scanned="17" subspace="\x15\x1a" target_index_name="[indexA, indexB, indexC, indexD]"
```

2022-11-07 21:56 UTC, jjezra commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
> +        if (interval == 0 || interval > (now - timeOfLastProgressLogMillis)) {
I can do that, but `TestHelpers.assertLogs` will not test the interval but just the existence of this message (appearing at first continuation - i.e. in any case of not indexing all in a single transaction).

2022-11-07 22:16 UTC, jjezra commented
```FDBRecordStoreIndexTest > testBoundaryPrimaryKeys() FAILED```

Test this please

2022-11-07 22:17 UTC, jjezra commented
Test this please

2022-11-07 22:28 UTC, jjezra commented
Squashed.

2022-11-08 11:15 UTC, alecgrieser requested changes

2022-11-08 13:35 UTC, jjezra commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingBase.java
> +        if (interval == 0 || interval > (now - timeOfLastProgressLogMillis)) {
✅

2022-11-08 13:44 UTC, jjezra commented on fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/OnlineIndexerSimpleTest.java
> +                .setProgressLogIntervalMillis(10)
✅

2022-11-08 14:29 UTC, alecgrieser approved these changes

2022-11-28 16:52 UTC, jleach4 approved these changes

2022-11-28 16:54 UTC, merged