Consider tighter protobuf performance by removing array copies #1921
FoundationDB/fdb-record-layer pull request #1922
Opened 2022-11-17 23:43 UTC by jleach4

Small nit but see a lot of object creation in production.

2022-11-17 23:59 UTC, MMcM requested changes

2022-11-17 23:59 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/InstrumentedTransaction.java
> +        System.out.println(String.format("Mutation {opType=%s, key=%s}", opType.name(), Base64.getEncoder().encodeToString(key)));
Leftover debugging code?

2022-11-17 23:59 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java
> +                System.out.println("mutation -> " + state.index.getType() + " : " + state.index);
More debugging?

2022-11-17 23:59 UTC, MMcM commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
> +        System.out.println("WTF?");
This too.

2022-11-18 00:08 UTC, jleach4 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/indexes/AtomicMutationIndexMaintainer.java
> +                System.out.println("mutation -> " + state.index.getType() + " : " + state.index);
oops

2022-11-18 00:09 UTC, jleach4 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/FDBRecordStore.java
> +        System.out.println("WTF?");
triple oops... wrong branch :(

2022-11-18 00:21 UTC, MMcM submitted a review, later dismissed

2022-11-18 10:33 UTC, alecgrieser approved these changes

2022-11-18 10:33 UTC, alecgrieser commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/cursors/FlatMapPipelinedCursor.java
> +                builder.setOuterContinuation(ZeroCopyByteString.wrap(outerResult.getContinuation().toBytes()));
I don't see a harm here in using a `ZeroCopyByteString`, but we should also consider using the `RecordCursorContinuation::toByteString` method on continuations in situations like these. The `toByteString` method is newer, and so not all of the continuations are updated, but for continuations that implement it, it should skip a copy (potentially more than one).

2022-11-18 10:34 UTC, merged