Lucene auto complete v2
FoundationDB/fdb-record-layer pull request #2079
Opened 2023-04-03 18:09 UTC by normen662

2023-04-03 18:58 UTC, MMcM requested changes

2023-04-03 18:58 UTC, MMcM commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java
> + * LuceneQueryMultiFieldSearchClause.java
```suggestion
 * LuceneAutoCompleteQueryClause.java
```

2023-04-04 19:12 UTC, normen662 commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneAutoCompleteQueryClause.java
> + * LuceneQueryMultiFieldSearchClause.java
done

2023-04-06 15:02 UTC, MMcM approved these changes

2023-04-06 15:03 UTC, merged