Add support for `int32` in record metadata `Value`
FoundationDB/fdb-record-layer pull request #2092
Opened 2023-04-13 19:21 UTC by hatyo

Currently decimal values are treated as `int64`, this could silently change the semantics of an `IndexPredicate` with a `SimpleComparison` that has an operand of type `Integer` as it is widening it into `long`.

This adds support for `int32`, it also adds a unit test that verifies that the serialisation / deserialisation of comparison parameters yield identical results. it fixes #2091 and unblocks https://github.com/FoundationDB/fdb-record-layer/pull/2070.

2023-04-13 19:46 UTC, MMcM requested changes
There is an `incorrectIntegerSerializationTest`, which can now be merged into `serializationTest`.

2023-04-14 10:19 UTC, hatyo commented
> There is an `incorrectIntegerSerializationTest`, which can now be merged into `serializationTest`.

Done.

2023-04-14 12:37 UTC, normen662 approved these changes

2023-04-14 18:32 UTC, MMcM approved these changes

2023-04-14 18:33 UTC, merged