Support promoting null to another type in PromoteValue.inject
FoundationDB/fdb-record-layer pull request #2255
Opened 2023-08-09 08:49 UTC by arnaud-lacurie

2023-08-09 08:49 UTC, arnaud-lacurie commented
@normen662 , where is a good place for me to test that additional piece of code?

2023-09-11 12:27 UTC, normen662 requested changes

2023-09-11 12:27 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java
> +        return resultType.isUnresolved() || resultType.getTypeCode() == Type.TypeCode.NULL;
can this happen?

2023-09-11 13:19 UTC, arnaud-lacurie commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java
> +        return resultType.isUnresolved() || resultType.getTypeCode() == Type.TypeCode.NULL;
Removed the `isUnresolved`

2023-09-11 13:29 UTC, normen662 approved these changes

2023-09-11 14:03 UTC, merged