Resolves #2293: Rethrow original IOExceptions in lucene code
FoundationDB/fdb-record-layer pull request #2294
Opened 2023-09-05 20:58 UTC by ScottDugas

We were wrapping them in UncheckedIOException, this creates two new helpers `LuceneOpener` and `LuceneCloseable` that make it easier to unwrap the exception appropriately, and close the lazily opened object correctly.

2023-10-05 19:36 UTC, ohadzeliger requested changes

2023-10-05 19:36 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +                () -> new CountingCloseable(openCounter.incrementAndGet(), closeCounter))) {
It may be more interesting to pass the openCounter itself to the CountingCloseable and increment it at the constructor

2023-10-05 19:36 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +        assertEquals(1, closeCounter.get());
Call `close()` multiple times? (This is to ensure the `LazyCloseable` doesn't do anything funky during close)

2023-10-05 19:36 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +    }
Add tests that use the `clone()` method? This is of particular interest for the way this is used...

2023-10-05 19:36 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +            closeCounter.incrementAndGet();
Should we add tests where the `close()` throws exception?

2023-10-05 19:36 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +        IOException thrownException = new IOException("test foo");
This does not assert on the counters, but the expectation is that they are 1 and 0, and that initialized == false?

2023-10-16 17:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/codec/LazyCloseableTest.java
> +    void testForkJoinPoolDeadlock() throws ExecutionException, InterruptedException, TimeoutException {
I was inspired to add this test, and the version on `LazyOpenerTest`, since this seems particularly important for our use case.

2023-10-16 21:07 UTC, ohadzeliger approved these changes
Approved. Build failures are for Style checks.

2023-10-20 16:21 UTC, ohadzeliger approved these changes

2023-10-20 16:21 UTC, merged