set update pipeline size == 1
FoundationDB/fdb-record-layer pull request #2323
Opened 2023-10-24 16:02 UTC by g31pranjal

2023-10-27 16:01 UTC, alecgrieser requested changes
This feels like we should call this out in the release notes, especially because this bug actually requires a response from any adopter that has defined a custom `PipelineSizer`

2023-10-27 16:51 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/PipelineOperation.java
> -    public static final PipelineOperation INSERT = new PipelineOperation("INSERT");
+1

2023-10-30 13:51 UTC, g31pranjal commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/plans/RecordQueryAbstractDataModificationPlan.java
> +                        store.getPipelineSize(PipelineOperation.UPDATE));
I think I am more convinced that the adopter, if they want, can have a custom value for the pipeline operation INSERT, UPDATE, DELETE. At least, it seems better than putting 1 there for now :D

2023-10-31 11:27 UTC, alecgrieser approved these changes

2023-10-31 11:31 UTC, merged