Resolves #2394: Lucene primary key segment index creates more segments than needed
FoundationDB/fdb-record-layer pull request #2395
Opened 2023-12-06 22:12 UTC by MMcM

2023-12-07 04:04 UTC, MMcM commented
`LuceneStoredFieldsTest .testDeleteAllDocuments` failure is due to the new delete approach managing to clean up all segments, rather than leaving one with all tombstoned documents. Probably the test fixture needs to assert on the number of _live_ documents.

2023-12-12 22:03 UTC, ScottDugas requested changes

2023-12-12 22:03 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
> +        assertThat(timer.getCount(LuceneEvents.Events.LUCENE_DELETE_DOCUMENT_BY_QUERY), lessThan(5));
Debugging this test against main, it looks like `LUCENE_FIND_MERGES` is 14, would it make sense to assert about that counter too? Locally it appears to be 4, which still seems higher than I would expect, but making sure it's less than 9 seems good. Of course that wouldn't apply if we defer merges. Deferring merges would also effect the segment count assertions.

2023-12-13 15:00 UTC, ScottDugas approved these changes

2023-12-13 15:00 UTC, merged