RESOLVES #2567: Lucene: Merge periodically when rebalancing a lot of …
FoundationDB/fdb-record-layer pull request #2568
Opened 2024-03-08 18:14 UTC by wshaib-apple

…documents

- default cap set by property to 1000

2024-03-08 20:35 UTC, jjezra requested changes

2024-03-08 20:35 UTC, jjezra commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexTest.java
> +        }
Nice test!
Can it be repeated with different variety of numbers? Something like: 
```
@Test 
void capDocCountMovedDuringRepartitioningTestA() throws IOException {
  capDocCountMovedDuringRepartitioningTest(/*docCount*/ 73, /*highWatermark*/ 23, /*transactionDocCount*/ 7);
}

@Test 
void capDocCountMovedDuringRepartitioningTestA() throws IOException {
  capDocCountMovedDuringRepartitioningTest(/*docCount*/ 17, /*highWatermark*/ 10, /*transactionDocCount*/ 3);
}

Etc. 
```

2024-03-08 20:35 UTC, jjezra commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneRecordContextProperties.java
> +    public static final RecordLayerPropertyKey<Integer> LUCENE_REPARTITION_MAX_DOCUMENT_COUNT = RecordLayerPropertyKey.integerPropertyKey("com.apple.foundationdb.record.lucene.repartition.max.documen
Would `LUCENE_MAX_DOCUMENTS_TO_MOVE_DURING_REBALANCE` (or something similar) be more descriptive?

2024-03-08 20:35 UTC, jjezra commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java
> +                                                        mergeControl.setRepartitionCapped(maxIterations.get() == 0);
How about 
```
 mergeControl.setRepartitionCapped(newContinuation.isEnd());
```
? 
(Just in case both conditions are met)

2024-03-08 20:35 UTC, jjezra commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/provider/foundationdb/IndexingMerger.java
> +        repartitionCapped = mergeControl.repartitionCapped();
It feels that this `repartitionCapped` should not be a member. Will you consider providing `mergeControl` as an argument to `shouldGiveRepartitionSecondChance`, and let that function keep the repartitioning knowledge?

2024-03-11 22:55 UTC, jjezra commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java
> +                                                        mergeControl.setRepartitionCapped(maxIterations.get() == 0);
Yep :)

2024-03-12 17:02 UTC, jjezra approved these changes

2024-03-12 17:29 UTC, ScottDugas approved these changes

2024-03-12 17:30 UTC, merged