Delegate `ConstantObjectValue`'s subsumption logic to semantic equals.
FoundationDB/fdb-record-layer pull request #2824
Opened 2024-07-15 15:44 UTC by hatyo

2024-07-16 11:24 UTC, normen662 requested changes

2024-07-16 11:24 UTC, normen662 commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/values/ConstantObjectValue.java
> +import com.apple.foundationdb.record.query.plan.cascades.ValueEquivalence;
Seems like an unused import.

2024-07-16 11:26 UTC, normen662 approved these changes

2024-07-16 13:13 UTC, normen662 approved these changes

2024-07-19 17:03 UTC, closed without merging

2024-07-19 17:18 UTC, hatyo commented
in favour of https://github.com/FoundationDB/fdb-record-layer/pull/2838