LuceneIndexMaintenanceTest: Use asyncToSync in a couple places
FoundationDB/fdb-record-layer pull request #2861
Opened 2024-08-01 13:11 UTC by ScottDugas

This will result in asyncToSync timeout instead of the test timing out.

2024-08-01 16:09 UTC, ohadzeliger requested changes

2024-08-01 16:09 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
> +                    LOGGER.debug("couldn't merge at iteration{}", i);
This will silently ignore all failures of the merger thread - should we ensure that at least some of them succeeded?

2024-08-01 16:09 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
>              for (int i = 0; i < countReps; i++) {
This merges in a very tight loop. Maybe adding some delay here to ease the load on the cluster?

2024-08-01 16:09 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
> +        assertThat(insertedDocs, Matchers.not(Matchers.anEmptyMap()));
Should we interrupt the threads (or add timeout at the Junit test level)?

2024-08-15 19:08 UTC, ohadzeliger submitted a review, later dismissed

2024-08-15 19:08 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
> +                                LOGGER.debug("couldn't commit for key {}", (1000L + i), e);
(This can be done some other time)

2024-08-16 20:34 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintenanceTest.java
> +                                LOGGER.debug("couldn't commit for key {}", (1000L + i), e);
I think there actually shouldn't be any other errors, so I can set it to fail the test if there are any other exceptions, but I will validate

2024-08-19 17:39 UTC, ohadzeliger approved these changes

2024-08-19 17:39 UTC, merged