Fixes #2881: VerifyException in Compensation if unmatched quantifiers is only non-empty thing requiring compensation
FoundationDB/fdb-record-layer pull request #2882
Opened 2024-08-15 18:56 UTC by alecgrieser

This updates the `VerifyException` in `Compensation` so that it does not reject inputs that `SelectExpression.compensate` expects to be able to hand to it.

This fixes #2881.

2024-08-16 17:39 UTC, hatyo requested changes

2024-08-16 17:39 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Compensation.java
> -            Verify.verify(!predicateCompensationMap.isEmpty() || remainingComputationValueOptional.isPresent());
For this particular case, the creation of the `Compensation` in `SelectExpression#compensate` is relevant for signalling the need of `Exists` to inject itself as a compensating `QueryPredicate` in the containing query fragment as in here: 

https://github.com/FoundationDB/fdb-record-layer/blob/c504a045f318da8bef5c611d9fa62579610c9a4f/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/predicates/ExistsPredicate.java#L212-L215

Moreover, a `Compensation` is something that is supposed to filter more rows and/or change the shape of the results, I think creating a compensation without a predicate nor a remaining computation is malformed, for more information, looks at the `apply` logic of `ForMatch`:

https://github.com/FoundationDB/fdb-record-layer/blob/c504a045f318da8bef5c611d9fa62579610c9a4f/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Compensation.java#L726-L735

we return immediately if we do not find a predicate in the compensation predicate map.

and therefore, if in your case, when we notice an unmatched quantifier only, we should probably create an impossible compensation instead, which, in addition to what I mentioned above, more efficient, considering that it is only used for triggering the injection of `Exists` itself as a compensation.

2024-08-16 17:39 UTC, hatyo commented on fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/Compensation.java
> -            Verify.verify(!predicateCompensationMap.isEmpty() || remainingComputationValueOptional.isPresent());
My suggestion is to change this block:

https://github.com/FoundationDB/fdb-record-layer/blob/c504a045f318da8bef5c611d9fa62579610c9a4f/fdb-record-layer-core/src/main/java/com/apple/foundationdb/record/query/plan/cascades/expressions/SelectExpression.java#L746-L751

to become something like this:

```java
final var isCompensationNeeded =
        !predicateCompensationMap.isEmpty() || matchInfo.getRemainingComputationValueOptional().isPresent();

if (!isCompensationNeeded) {
    if (!unmatchedQuantifiers.isEmpty()) {
        return Compensation.impossibleCompensation();
    }
    return Compensation.noCompensation();
}
```

2024-08-19 18:47 UTC, normen662 commented
This is fixed in #2888. The test case from this PR is used verbatim in #2888. The problem that is exposed by this problem goes further than just the check. It is possible that a particular compensation is required but we never use the necessary quantifiers during the pull-up logic in `Compensation`. @hatyo and I debugged this today and we are pretty sure to have gotten to the bottom of this one.

2024-08-19 18:48 UTC, closed without merging