Lucene: AnalyzerChooser no longer takes the text when choosing an analyzer
FoundationDB/fdb-record-layer pull request #2994
Opened 2024-12-05 19:16 UTC by ScottDugas

This removes the option for having `AnalyzerChooser` pick the analyzer based on the contents of the query.
This moves it so that the `FDBDirectoryManager` creates one `LuceneAnalyzerWrapper`, and preserves it for the transaction.
Eventually this will allow `FDBDirectoryWrapper` to have the writer be lazy but final, but I didn't bring that change into here, isolating this to the breaking change.

This Resolves #2993

2025-03-17 20:20 UTC, ScottDugas commented
Looking at the failure for `other-tests`, it appears that `flakyMergeQuick()` failed.
https://github.com/FoundationDB/fdb-record-layer/actions/runs/13904136879?pr=2994
I tried many times locally to reproduce this, but couldn't.
It appears that in the PRB it successfully merged after iteration 27, and then it tried to assert that there were no duplicates in the PrimaryKeySegmentIndex. There were duplicates. 

It's not a fast test, but so far as I can tell, locally, it never has a successful merge. 

I suspect this is an issue with the use of `asyncToSyncTimeout` to inject failures, and not a regression as part of this change.

2025-03-20 16:12 UTC, ohadzeliger requested changes

2025-03-21 13:33 UTC, ScottDugas commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/LuceneIndexMaintainer.java
> +    private final LuceneAnalyzerCombinationProvider queryAnalyzerSelector;
There isn't really a thread safety concern.
I didn't want to have `LuceneIndexMaintainer` pass the `LuceneAnalyzerCombinationProvider` the `DirectoryManager`, because the `DirectoryManager` is cached in the context, but a new `LuceneIndexMaintainer` is created for every operation (e.g. a record save or scan).
Instead, I added a field, and getter to `DirectoryManager` to get the one it creates, and the `LuceneIndexMaintainer` uses that now.

2025-03-21 13:33 UTC, ScottDugas commented on fdb-record-layer-lucene/src/main/java/com/apple/foundationdb/record/lucene/directory/FDBDirectoryWrapper.java
> -                    writerAnalyzerId = analyzerWrapper.getUniqueIdentifier();
We could, it's used by one test to check that the write wrapper is created. Looking a bit further though, once we rework that test to not depend on the unique identifier, there's no reason to have `LuceneAnalyzerWrapper` at all, so I created: https://github.com/FoundationDB/fdb-record-layer/issues/3265 to remove that entirely.

2025-03-24 18:07 UTC, ohadzeliger approved these changes

2025-03-24 20:04 UTC, merged