Refactor LuceneFailreTest to use the DataModel, not LuceneTestBase
FoundationDB/fdb-record-layer pull request #3010
Opened 2024-12-20 22:31 UTC by ohadzeliger

2025-01-03 21:24 UTC, ScottDugas requested changes

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +        long docGroupFieldValue = groupingKey.isEmpty() ? 0L : groupingKey.getLong(0);
`groupingKey` is always `Tuple.from(1L)`, would it make sense to reorder the assignments:
```java
long docGroupFieldValue = 1L;
Tuple groupingKey = Tuple.from(docGroupFieldValue);
```

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +                .setPartitionHighWatermark(10)
It might be worth extracting this into a variable, and making `totalDocCount` a function of it, e.g.:
```java
final int partitionHighWatermark = 10;
final int totalDocCount = partitionHighWatermark * 2;
```

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
>          try (FDBRecordContext context = openContext(contextProps)) {
You could probably just call:
```java
dataModel.validate(() -> openContext(contextProps));
```
It will assert that the documents align, and that the partitions are all an acceptable size. It is less strict than the assertions here, but it is probably less brittle in the long run.

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +                .setPartitionHighWatermark(10)
Based on the comment above, should this be:
```suggestion
                .setPartitionHighWatermark(totalDocCount)
```

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +        int docGroupFieldValue = groupingKey.isEmpty() ? 0 : (int)groupingKey.getLong(0);
Here, also, would it be worth rearranging so that the `groupingKey` is derived from `docGroupFieldValue`

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +                dataModel.saveRecord(start - i - 1, store, docGroupFieldValue);
Why are you decrementing the `start` here?

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +            dataModel.saveRecord(2, store, docGroupFieldValue);
This is not updating a record, it is saving a new record. You'll want to use 
```java
dataModel.recordsUnderTest().forEach(record -> record.updateOtherValue(store));
```

2025-01-03 21:24 UTC, ScottDugas commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
>      private void setupExceptionMapping(boolean useExceptionMapping) {
Why have the two different methods?

2025-01-13 22:14 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> +                    new FDBExceptions.FDBStoreTransactionIsTooOldException("Blah", new FDBException("Blah", 7)),
The new method replaces two test methods: One with `AsyncToSyncTimeoutException` and one with `DBStoreTransactionIsTooOldException`. The new test method has an additional parameter (`isGrouped`) and throws `DBStoreTransactionIsTooOldException`.

2025-01-13 22:19 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
> -            injectedFailures.addFailure(LUCENE_GET_FDB_LUCENE_FILE_REFERENCE_ASYNC,
Before, there were two test methods (one for Grouped and one for Ungrouped search). I don't remember exactly why the injection was added at the top and I believe your reasoning is correct - the `bind` call for the creation of the scan bounds loaded the cache.
Once refactored the code and consolidated the two method, it made sense to move the injection below the `save` as it offers more direct relationship to the action action being carried out.

2025-01-13 22:34 UTC, ohadzeliger commented on fdb-record-layer-lucene/src/test/java/com/apple/foundationdb/record/lucene/FDBLuceneIndexFailureTest.java
>          try (FDBRecordContext context = openContext(contextProps)) {
Do you mean to replace the entire `try` block with both `validateDocsInPartition` in it? In that case, it would probably also make sense to change the original in `LuceneIndexTest`?

2026-05-27 20:06 UTC, closed without merging